[WIP] Add Chinese version of index page
cilium/ebpf.io pull request #8
Opened 2020-08-13 18:25 UTC by nevermosby

This PR is to add Chinese version of index page so that `ebpf.io` can support multi-language.

**It is WIP and will complete it before the end of this week.**

2020-08-15 05:48 UTC, nevermosby commented
Hi, this PR has been done as I have translated most of index.js into Chinese. Pls help review it. Thx.

2020-10-07 18:44 UTC, joestringer commented
:wave: @nevermosby , thanks for the submission!

Netlify seems to be having some trouble trying to render this PR:

```
10:38:15 PM:   Error: ./~/babel-loader/lib?{"plugins":["/opt/build/repo/~/gatsby/dist/utils/b  abel-plugin-extract-graphql.js","/opt/build/repo/~/babel-plugin-add-module-exp  orts/lib/index.js","/opt/build/repo/~/babel-plugin-transform-object-assign/lib  /index.js"],"presets":[["/opt/build/repo/~/babel-preset-env/lib/index.js",{"lo  ose":true,"uglify":true,"modules":"commonjs","targets":{"browsers":["> 1%","la  st 2 versions","IE >= 9"]},"exclude":["transform-regenerator","transform-es201  5-typeof-symbol"]}],"/opt/build/repo/~/babel-preset-stage-0/lib/index.js","/op  t/build/repo/~/babel-preset-react/lib/index.js"],"cacheDirectory":true}!./src/  pages/zh-CN/index.js
10:38:15 PM:   Module not found: Error: Cannot resolve 'file' or 'directory' ../stylesheets/i  ndex.scss in /opt/build/repo/src/pages/zh-CN
10:38:15 PM:   resolve file
10:38:15 PM:     /opt/build/repo/src/pages/stylesheets/index.scss.js doesn't exist
    /opt/build/repo/src/pages/stylesheets/index.scss.jsx doesn't exist
    /opt/build/repo/src/pages/stylesheets/index.scss doesn't exist
  resolve directory
10:38:15 PM:     /opt/build/repo/src/pages/stylesheets/index.scss doesn't exist (directory de  fault file)
    /opt/build/repo/src/pages/stylesheets/index.scss/package.json doesn't exist   (directory description file)
  [/opt/build/repo/src/pages/stylesheets/index.scss.js]
10:38:15 PM:   [/opt/build/repo/src/pages/stylesheets/index.scss.jsx]
10:38:15 PM:   [/opt/build/repo/src/pages/stylesheets/index.scss]
10:38:15 PM:    @ ./~/babel-loader/lib?{"plugins":["/opt/build/repo/~/gatsby/dist/utils/babel  -plugin-extract-graphql.js","/opt/build/repo/~/babel-plugin-add-module-exports  /lib/index.js","/opt/build/repo/~/babel-plugin-transform-object-assign/lib/ind  ex.js"],"presets":[["/opt/build/repo/~/babel-preset-env/lib/index.js",{"loose"  :true,"uglify":true,"modules":"commonjs","targets":{"browsers":["> 1%","last 2   versions","IE >= 9"]},"exclude":["transform-regenerator","transform-es2015-ty  peof-symbol"]}],"/opt/build/repo/~/babel-preset-stage-0/lib/index.js","/opt/bu  ild/repo/~/babel-preset-react/lib/index.js"],"cacheDirectory":true}!./src/page  s/zh-CN/index.js 23:0-36
```

I think we need to figure out why this is and resolve it first. Were you able to build & view the changes locally?

2020-10-07 18:48 UTC, genbit requested changes
need to fix relative paths

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +import "../stylesheets/index.scss";
this need to be 
```
import "../../stylesheets/index.scss";
```

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +    <img className="main-logo" src={require("../assets/logo-big.png")} />
needs to be 
```
    <img className="main-logo" src={require("../../assets/logo-big.png")} />
```

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +    <img src={require("../assets/go.png")} />
```
    <img src={require("../../assets/go.png")} />
```

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +        icon={require("../assets/intro_security.png")}
```
        icon={require("../../assets/intro_security.png")}
```

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +        icon={require("../assets/intro_networking.png")}
```
        icon={require("../../assets/intro_networking.png")}
```

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +        icon={require("../assets/intro_tracing.png")}
```
        icon={require("../../assets/intro_tracing.png")}
```

2020-10-07 18:48 UTC, genbit commented on src/pages/zh-CN/index.js
> +        icon={require("../assets/intro_observability.png")}
```
        icon={require("../../assets/intro_observability.png")}
```

2020-10-10 18:37 UTC, nevermosby commented
@genbit thx for remind and I have fixed the wrong code.

@joestringer thx for review and pls help review again.

2020-10-10 19:08 UTC, joestringer approved these changes
Text LGTM, though I couldn't figure out how to switch locales to observe the page in-place with the netlify preview.

2020-10-12 04:22 UTC, genbit commented
> Text LGTM, though I couldn't figure out how to switch locales to observe the page in-place with the netlify preview.

@joestringer I don't think we have support for locale switching yet, we need to add support for it.

There are two options:

1. Add manual switching only - flags that basically goes to different pages
2. Add automatic locale detection based on IP and redirect to appropriate page. Netlify supports it - https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language

2020-10-12 04:24 UTC, genbit commented
@joestringer if you just want to look at the page: https://deploy-preview-8--ebpfio.netlify.app/zh-CN/

2020-10-19 22:13 UTC, joestringer commented
@genbit do you want @nevermosby to take a crack at adding that support before merging this PR or are you happy to merge this as-is then someone can add locale switching afterwards?

2020-10-20 19:19 UTC, genbit commented
@joestringer I'm ok with both as long as we track and have that someone to do redirect switching. If we close PR, we might just forget about it.

2021-02-03 17:04 UTC, qmonnet commented
The Chinese translation is now merged via #96, and live on the website (see language selector at the top). Thanks a lot @nevermosby!

2021-02-03 17:04 UTC, closed without merging